	\context ChordNames
		\chords {
		\set chordChanges = ##t

		% intro
		a2:m a2:m/g
		a2:m/fis a2:m/f

		a2:m a2:m/g
		a2:m/fis a2:m/f

		% vino y pan hoy te ofrecemos...
		a2:m a2:m/g
		a2:m/fis a2:m/f
		d2:m g2 c2 e2

		% presentamos el esfuerzo...
		a2:m a2:m/g
		a2:m/fis a2:m/f
		d2:m g2 c1 e1

		% pues la vida es una viña...
		a2 e2 fis2:m cis2:m
		b1:m d2 e2

		% y el pan que presentamos...
		a2 e2 fis2:m cis2:m
		d1 b1:m g1 e1

		% bendito seas...
		a2 e2/a d2/a e2/a
		a2 e2/a d2/a e2/a
		fis2:m d2
		b2:m e1

		% bendito seas...
		a2 e2 d2 e2
		a2 e2 d2 e2
		fis2:m d2
		b2:m e2 a1

		% interludio
		a2:m a2:m/g
		a2:m/fis a2:m/f

		a2:m a2:m/g
		a2:m/fis a2:m/f

		% nuestra fe, nuestra esperanza...
		a2:m a2:m/g
		a2:m/fis a2:m/f
		d2:m g2 c2 e2

		% que tu amor hoy las reciba...
		a2:m a2:m/g
		a2:m/fis a2:m/f
		d2:m g2 c1 e1

		% pues la vida es una viña...
		a2 e2 fis2:m cis2:m
		b1:m d2 e2

		% y el pan que presentamos...
		a2 e2 fis2:m cis2:m
		d1 b1:m g1 e1

		% bendito seas...
		a2 e2/a d2/a e2/a
		a2 e2/a d2/a e2/a
		fis2:m d2
		b2:m e1

		% bendito seas...
		a2 e2 d2 e2
		a2 e2 d2 e2
		fis2:m d2
		b2:m e2 a1
		b2:m e2 a1
		b2:m e2 a1
		a1
		}
